import { Footer } from "@/components/footer/Footer";
import { NavBar } from "@/components/nav_bar/NavBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <div className="container">
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
